### ISSUE TITLE
can't run?

### ISSUE THREAD

**Issue by sunhoro** [vd1371/GIAMS#2] opened 2022-07-25 01:26 UTC
Did anyone try running GIAMS? It seemed interesting enough to try it out. But I can not even run it on the very first try.
Not sure why but seems to have numpy version issue (mine is all up to date).
Can anyone see what the solution is? below is the error script.

------------------------------------------------------------------------------------------

C:\Users\User\Downloads\GIAMS-master>run.py
C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py:138: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\GIAMS-master\run.py", line 5, in <module>
    import Examples as Ex
  File "C:\Users\User\Downloads\GIAMS-master\Examples\__init__.py", line 2, in <module>
    from . import Example1
  File "C:\Users\User\Downloads\GIAMS-master\Examples\Example1.py", line 10, in <module>
    from Network import IndianaNetwork
  File "C:\Users\User\Downloads\GIAMS-master\Network\__init__.py", line 1, in <module>
    from .IndianaNetwork import IndianaNetwork
  File "C:\Users\User\Downloads\GIAMS-master\Network\IndianaNetwork.py", line 1, in <module>
    import numpy as np
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "C:\ProgramData\Anaconda3\python.exe"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

**Comment by vd1371** [comment] 2022-07-25 12:12
Hi, thanks for showing interest in it.

I'm basically the only person who manages GIAMS. As result, it might take a little bit longer for problems to be solved.
I will try my best to address and hopefully solve the problem by the end of this week.

Thanks for your patience in advance.

**Comment by vd1371** [comment] 2022-08-01 01:20
Hi,

I went back to the code and fixed a minor bug, but not related to your issue.

Can you please run the code without Anaconda?
Simply install python from the main website: https://www.python.org/
(mine is 3.8.7)
Then install all other dependencies and see if the problem still exists.

Please do let me know if it worked or not.

**Comment by sunhoro** [comment] 2022-08-01 03:37
> Hi,
> 
> I went back to the code and fixed a minor bug, but not related to your issue.
> 
> Can you please run the code without Anaconda? Simply install python from the main website: https://www.python.org/ (mine is 3.8.7) Then install all other dependencies and see if the problem still exists.
> 
> Please do let me know if it worked or not.

I tried it without Anaconda on 3 different computers and still the same issue.
All python packages are up-to-date and run.py does not work (the script disappears in 0.5 sec)
Trying it on cmd still shows same issue. Mostly something to do with numpy.

What else can I try?

**Comment by vd1371** [comment] 2022-08-01 05:17
After reading a bit more on the web and doing more research on the error, I'm pretty sure the issue is not related to the GIAMS framework.

Therefore, I highly recommend you take care of the setup problem of your numpy and python.

Some of the links that can be useful:

https://stackoverflow.com/questions/58868528/importing-the-numpy-c-extensions-failed

https://numpy.org/devdocs/user/troubleshooting-importerror.html

https://stackoverflow.com/questions/68967514/importing-the-numpy-c-extensions-failed-amplify

If you have installed numpy with "conda", you can try and install it using pip and see if the problem still persists.

**Comment by sunhoro** [comment] 2022-08-04 14:55
Thanks for the help.
But I may be misunderstanding how this project works.
If you could, can you briefly go over step-by-step how to start and use GIAMS?
I'm quite sure python and all the necessary tools are installed. 
Thank you,

**Comment by vd1371** [comment] 2022-08-05 06:10
Please contact me personally so we can discuss it further: vd1371@gmail.com

Also, please read the original paper of GIAMS before setting a meeting:
https://www.sciencedirect.com/science/article/abs/pii/S0926580521001436

I'm closing this issue bcs the technical problem is solved apparently.

**Closed as completed by vd1371** 2022-08-05 06:10 UTC
